version: '4'
services:

  webapp:
    build: .
    restart: on-failure
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "8085:8080"
    environment:
      - SPRING_DATA_MONGODB_USERNAME=devDorian
      - SPRING_DATA_MONGODB_PASSWORD=devDorianPass
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_DATABASE=user-auth-service
      - SPRING_DATA_MONGODB_PORT=27017
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dorian
      - MONGO_INITDB_ROOT_PASSWORD=dorian01
    volumes:
      - mongodata:/data/db
      - type: bind
        source: ./mongo-entrypoint
        target: /docker-entrypoint-initdb.d
    healthcheck:
      test: echo 'db.runCommand({find:"user-auth-service.devDorian"}).ok' | mongosh --authenticationDatabase admin --host localhost -u dorian -p dorian01 admin --quiet | grep -q 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
volumes:
  mongodata:
